#!/usr/bin/env python


import gzip
import struct


def main(zipped):
  with gzip.open(zipped) as f:
    while True:
      try:
        length = struct.unpack('i', f.read(4))[0]
      except struct.error:
        break
      fn = f.read(length * 2).decode('utf-16')
      print(fn)
      length = struct.unpack('i', f.read(4))[0]
      with open(fn, 'wb') as fw:
        fw.write(f.read(length))


if __name__ == '__main__':
  import sys
  main(sys.argv[1])
